install.packages("igraph")
install.packages("networkD3")
install.packages("ggraph")
install.packages("ggplot2")
install.packages("udpipe")
install.packages("dplyr")
install.packages("devtools")
installGithub.r("cbail/textnets")
